### ISSUE TITLE
Middleware cannot be used if successive ones depend on omitted headers

### ISSUE THREAD

**Issue by srishanbhattarai** [mesaugat/express-filestack#3]
For example, if we omit the `Authorization` header:

```js
router.post('/some-route', filestack({ omitHeaders: ['Authorization'] }), someOtherMiddleware)
```

The `someOtherMiddleware` no longer has access to `Authorization`. The omitted headers should be restored before calling `next()`.

**Comment by mesaugat** [comment]
Good catch this. 👍
